# Define program version

set(XTRKCAD_MAJOR_VERSION "5")
set(XTRKCAD_MINOR_VERSION "3")
set(XTRKCAD_RELEASE_VERSION "1")
set(XTRKCAD_VERSION_MODIFIER "GA")
set(XTRKCAD_VERSION "${XTRKCAD_MAJOR_VERSION}.${XTRKCAD_MINOR_VERSION}.${XTRKCAD_RELEASE_VERSION}${XTRKCAD_VERSION_MODIFIER}")
