#!/bin/bash
if [ $# -ne 1 ] ; then
	echo "$0 <BLDDIR>/distribution/flatpak"
	echo "Create source tar ball, with .xpm3 files"
	echo "Run from <SRCDIR>/distribution/flatpak"
	echo "Computes sha256 checksum which must updated in org.xtrkcad.xtrkcad.yml"
	exit 0
fi

SRCDIR=`pwd`
BLDDIR=$1

cd ../..
tar cf ${BLDDIR}/source.tar .
cd $BLDDIR/../../app/bin
tar rf ${BLDDIR}/source.tar ./bitmaps

cd $BLDDIR
rm -f source.tar.gz
# -n zeros the timestamp so repeated runs yield the same checksum
gzip -n source.tar
echo "Update org.xtrkcad.xtrkcad.yml with this checksum"
sha256sum source.tar.gz
